### ISSUE TITLE
setting colorbar range and missing values in ds.plot

### ISSUE THREAD

**Issue by jhjhagen** [maartenbreddels/vaex#89]
When using ds.plot without entering vmin, vmax, missing values will be transparant:

```python
_#UV-plot
#Plot 1:
vmin=None
vmax=None

#Plot 2:
#vmin=0.0
#vmax=5.0

limits=None
limits=[[-130,130],[-120,60]]
fig=plt.figure()
ds.plot(x='vx',y='vy', selection=True, aspect='auto', colormap=cmap, limits=limits, f=func, shape=shape,vmin=vmin,vmax=vmax)
plt.xlabel('U [km/s]', fontsize=fontsize)
plt.ylabel('V [km/s]', fontsize=fontsize)
plt.xticks(fontsize=fontsize2)
plt.yticks(fontsize=fontsize2)
plt.xlim(limits[0])
plt.ylim(limits[1])
cb = fig.axes[-1]
cb.tick_params(labelsize=fontsize)
cb.set_ylabel(r'$^{10}\log$(N)', fontsize=fontsize)
plt.show()_
```

![image](https://user-images.githubusercontent.com/23260614/40166883-f3424914-59bf-11e8-866e-198449d8018f.png)

Though when setting vmin and vmax (both are apparently required for vaex to work), the nan's get assigned vmin. I'd like to prevend this from happening:

![image](https://user-images.githubusercontent.com/23260614/40167138-85bd05a4-59c0-11e8-890e-d776e8e71b6e.png)

**Comment by maartenbreddels** [comment]
Thanks for the report, it is solved in the mentioned commit (will install it at the institute asap)

**Comment by jhjhagen** [comment]
Hi,

Thanks for the update on the transparancy. Though, it is still not possible to set _either_ vmin _or_ vmax. To complete the functionality of ds.plot I think this should be made possible.
